name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/docker-image.yml'

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
    
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        tags: devopsteamsdb/devopsteamsdb:pip2go_${{ steps.date.outputs.date }}
        file: Dockerfile
    
    - name: run container 
      run: docker run -rmi devopsteamsdb/devopsteamsdb:pip2go_${{ steps.date.outputs.date }}
    

