name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/docker-image.yml'

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"

    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Print Public IP
      run: |
        echo "Public IPv4: ${{ steps.ip.outputs.ipv4 }}"
        echo "Public IPv6: ${{ steps.ip.outputs.ipv6 }}"
        
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        tags: devopsteamsdb/devopsteamsdb:pip2go_${{ steps.date.outputs.date }}
        file: Dockerfile
    
    - name: run container 
      run: docker run devopsteamsdb/devopsteamsdb:pip2go_${{ steps.date.outputs.date }}
    

    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: devopsteamsdb/devopsteamsdb:pip2go_${{ steps.date.outputs.date }}
        file: Dockerfile
 
